name: GLaDOS 多账号自动签到

on:
  schedule:
    # 每天北京时间上午8-10点之间随机执行
    - cron: '0 0-2 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  checkin:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置随机延迟
      run: |
        # 生成0-120分钟的随机延迟（8-10点之间）
        DELAY_MINUTES=$((RANDOM % 120))
        echo "DELAY_MINUTES=$DELAY_MINUTES" >> $GITHUB_ENV
        echo "将在 $DELAY_MINUTES 分钟后执行签到"
        
    - name: 等待随机时间
      run: |
        echo "等待 $DELAY_MINUTES 分钟..."
        sleep $((DELAY_MINUTES * 60))
        
    - name: 执行多账号签到
      env:
        BARK_URL: ${{ secrets.BARK_URL }}
        BARK_KEY: ${{ secrets.BARK_KEY }}
        # 多账号配置 - 支持最多5个账号
        ACCOUNT1_COOKIE: ${{ secrets.ACCOUNT1_COOKIE }}
        ACCOUNT1_NAME: ${{ secrets.ACCOUNT1_NAME }}
        ACCOUNT2_COOKIE: ${{ secrets.ACCOUNT2_COOKIE }}
        ACCOUNT2_NAME: ${{ secrets.ACCOUNT2_NAME }}
        ACCOUNT3_COOKIE: ${{ secrets.ACCOUNT3_COOKIE }}
        ACCOUNT3_NAME: ${{ secrets.ACCOUNT3_NAME }}
        ACCOUNT4_COOKIE: ${{ secrets.ACCOUNT4_COOKIE }}
        ACCOUNT4_NAME: ${{ secrets.ACCOUNT4_NAME }}
        ACCOUNT5_COOKIE: ${{ secrets.ACCOUNT5_COOKIE }}
        ACCOUNT5_NAME: ${{ secrets.ACCOUNT5_NAME }}
      run: |
        chmod +x ./scripts/glados-checkin.sh
        ./scripts/glados-checkin.sh
        
    - name: 上传签到日志
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: checkin-logs-${{ github.run_number }}
        path: |
          api.log
          sign.log
          multi-account.log
